### ISSUE TITLE
Comentario inválido

### ISSUE THREAD

**Issue by navarroaxel** [felitra/TP-0-Felitti-Renzo#2]
Debe ser qué, quien, cuando.

``` C
/* Imprime en pantalla "Hello world"
* Felitti Renzo 
* 06/04/2015
*/
```

**Comment by felitra** [comment]
Buenas, me podria decir donde ve eso profesor ? https://github.com/felitra/TP-0-Felitti-Renzo/blob/master/Hello%20World.c Le dejo el link, no encuentro el comentario que usted menciona. Agregaré la última fecha de modificación que si me esta faltando
 Saludos

**Comment by navarroaxel** [comment]
Hola, el comentario que te puse es como debería ser (El qué es sólo un ejemplo) según las normas de la cátedra.

Gracias, pero no soy profesor =)

Saludos.-

**Comment by felitra** [comment]
Me refiero a que mi .c no tiene esos comentarios citados, pensé que eras profesor jaja. Fijate el link que te mande ... 

```
 On Sunday, April 26, 2015 4:59 PM, Axel Navarro <notifications@github.com> wrote:
```

 Hola, el comentario que te puse es como debería ser (El qué es sólo un ejemplo) según las normas de la cátedra.Gracias, pero no soy profesor =)Saludos.-—

**Comment by navarroaxel** [comment]
Este es tu comentario:

``` C
/*
 ============================================================================
 Name        : Hello.c
 Author      : Felitti Renzo
 Version     : 1.0
 Last Modification   : 6/4/2015
 Description : Hello World in C, Ansi-style
 ============================================================================
 */
```

Así es como debería ser formateado para cumplir las reglas de cátedra:

``` C
/* Hello World in C, Ansi-style
* Felitti Renzo 
* 06/04/2015
*/
```

**Comment by felitra** [comment]
En serio importa el orden ? ... 
Ok lo cambiare ... 

```
 On Sunday, April 26, 2015 5:04 PM, Axel Navarro <notifications@github.com> wrote:
```

 Este es tu comentario:/*
 ============================================================================
 Name        : Hello.c
 Author      : Felitti Renzo
 Version     : 1.0
 Last Modification   : 6/4/2015
 Description : Hello World in C, Ansi-style
 ============================================================================
 _/Así es como debería ser formateado para cumplir las reglas de cátedra:/_ Hello World in C, Ansi-style
- Felitti Renzo 
- 06/04/2015
  */—
